name: CI

on:
  push:
    branches: [ main, fix/workflow-trigger ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend unit tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: AlvrynAI/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        env:
          CI: true
        run: npm test --silent

  integration-smoke:
    name: Integration smoke (docker-compose)
    runs-on: ubuntu-22.04
    needs: backend-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start services with docker compose
        run: |
          cd AlvrynAI
          docker compose up -d --build

      - name: Wait for backend to become healthy
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:4000/ >/dev/null; then
              echo "backend up" && break;
            fi
            echo "waiting for backend... ($i)";
            sleep 2;
          done

      - name: Run integration smoke tests
        run: |
          cd AlvrynAI
          node ./scripts/integration/run_integration_test.js

      - name: Tear down
        if: always()
        run: |
          cd AlvrynAI
          docker compose down --volumes
